# Generated by Django 2.0.6 on 2018-06-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0002_yellowantredirectstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agile_Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGILE_API_KEY', models.CharField(max_length=256)),
                ('AGILE_EMAIL_ID', models.CharField(max_length=256)),
                ('AGILE_DOMAIN_NAME', models.CharField(max_length=256)),
                ('AGILE_UPDATE_LOGIN_FLAG', models.BooleanField(default=False)),
                ('user_integration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yellowant_api.UserIntegration')),
            ],
        ),
    ]
