# Generated by Django 2.0.6 on 2018-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0006_auto_20180626_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xero_credentials',
            name='XERO_STATE',
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_CONSUMER_KEY',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_CONSUMER_SECRET',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
