# Generated by Django 2.0.6 on 2018-06-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0008_auto_20180626_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xero_credentials',
            name='AGILE_API_KEY',
        ),
        migrations.RemoveField(
            model_name='xero_credentials',
            name='AGILE_UPDATE_LOGIN_FLAG',
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_CONSUMER_KEY',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_CONSUMER_SECRET',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_UPDATE_LOGIN_FLAG',
            field=models.BooleanField(default=False),
        ),
    ]
