# Generated by Django 2.0.6 on 2018-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0009_auto_20180626_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xero_credentials',
            name='XERO_CONSUMER_KEY',
        ),
        migrations.RemoveField(
            model_name='xero_credentials',
            name='XERO_CONSUMER_SECRET',
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_SECRET',
            field=models.CharField(default=0, max_length=512),
        ),
    ]
