# Generated by Django 2.0.6 on 2018-06-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0010_auto_20180627_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xero_credentials',
            name='XERO_SECRET',
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_AUTH_EXPIRE',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_EXPIRE',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_OAUTH_SECRET',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='xero_credentials',
            name='XERO_OAUTH_TOKEN',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
